- name: "play1-on master"
  hosts: localhost
  become: true
  tasks:
  - name: installing java and jenkins
    script: apache.sh

- name: "play2-on nodes"
  hosts: node2
  become: true
  tasks:
  - name: installing java and docker
    script: nginx.sh
